version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
